# In lesson exercise

In [1]:
import pandas as pd

In [2]:
import time

print("Loading data file now, this could take a while depending on file size")
start = time.time()
df = pd.read_csv('../data/Hotel_Reviews.csv')
end = time.time()
print("Loading took " + str(round(end - start, 2)) + " seconds")

Loading data file now, this could take a while depending on file size
Loading took 2.29 seconds

In [3]:
print("The shape of the data (rows, cols) is" + str(df.shape))

The shape of the data (rows, cols) is(515738, 17)

In [4]:
nationality_freq = df["Reviewer_Nationality"].value_counts()
print("There are " + str(nationality_freq.size) + "different nationalities")
print(nationality_freq)

There are 227different nationalities
Reviewer_Nationality
United Kingdom               245246
United States of America      35437
Australia                     21686
Ireland                       14827
United Arab Emirates          10235
                              ...
Cape Verde                        1
Northern Mariana Islands          1
Tuvalu                            1
Guinea                            1
Palau                             1
Name: count, Length: 227, dtype: int64

In [5]:
print("The highest frequency reviewer nationality is " + str(nationality_freq.index[0]).strip() + " with " + str(nationality_freq.iloc[0]) + " reviews")
print("The next 10 highest frequency reviewer nationalities are: ")
print(nationality_freq[1:11].to_string())

The highest frequency reviewer nationality is United Kingdom with 245246 reviews
The next 10 highest frequency reviewer nationalities are:
Reviewer_Nationality
United States of America     35437
Australia                    21686
Ireland                      14827
United Arab Emirates         10235
Saudi Arabia                  8951
Netherlands                   8772
Switzerland                   8678
Germany                       7941
Canada                        7894
France                        7296

In [7]:
df['Calc_Average_Score'] = round(df.groupby('Hotel_Name')['Reviewer_Score'].transform('mean'), 1)

In [8]:
display(df[['Hotel_Name', 'Average_Score', 'Calc_Average_Score']].head(10))

    Hotel_Name  Average_Score  Calc_Average_Score
0  Hotel Arena            7.7                 7.8
1  Hotel Arena            7.7                 7.8
2  Hotel Arena            7.7                 7.8
3  Hotel Arena            7.7                 7.8
4  Hotel Arena            7.7                 7.8
5  Hotel Arena            7.7                 7.8
6  Hotel Arena            7.7                 7.8
7  Hotel Arena            7.7                 7.8
8  Hotel Arena            7.7                 7.8
9  Hotel Arena            7.7                 7.8

In [9]:
df["Average_Score_Difference"] = df.apply(lambda x: x['Average_Score'] - x['Calc_Average_Score'], axis=1)

In [10]:
display(df[['Hotel_Name', 'Average_Score', 'Calc_Average_Score', 'Average_Score_Difference']].head(10))

    Hotel_Name  Average_Score  Calc_Average_Score  Average_Score_Difference
0  Hotel Arena            7.7                 7.8                      -0.1
1  Hotel Arena            7.7                 7.8                      -0.1
2  Hotel Arena            7.7                 7.8                      -0.1
3  Hotel Arena            7.7                 7.8                      -0.1
4  Hotel Arena            7.7                 7.8                      -0.1
5  Hotel Arena            7.7                 7.8                      -0.1
6  Hotel Arena            7.7                 7.8                      -0.1
7  Hotel Arena            7.7                 7.8                      -0.1
8  Hotel Arena            7.7                 7.8                      -0.1
9  Hotel Arena            7.7                 7.8                      -0.1

In [11]:
review_scores_df = df.drop_duplicates(subset=['Hotel_Name'])
review_scores_df = review_scores_df.sort_values(by=['Average_Score_Difference'])
display(review_scores_df[['Average_Score_Difference', 'Average_Score', 'Calc_Average_Score', 'Hotel_Name']].head(10))

,Average_Score_Difference,Average_Score,Calc_Average_Score,Hotel_Name
495945,-0.8,7.7,8.5,Best Western Hotel Astoria
111027,-0.7,8.8,9.5,Hotel Stendhal Place Vend me Paris MGallery by...
43688,-0.7,7.5,8.2,Mercure Paris Porte d Orleans
178253,-0.7,7.9,8.6,Renaissance Paris Vendome Hotel
71274,-0.5,8.9,9.4,Drawing Hotel
54745,-0.5,8.6,9.1,Hotel Les Rives de Notre Dame
257749,-0.5,7.5,8.0,Hotel De Vigny
218258,-0.5,7.0,7.5,Hotel Royal Elys es
190062,-0.4,8.9,9.3,H tel Saint Paul Rive Gauche
195491,-0.4,8.2,8.6,Pershing Hall

In [12]:
no_negative_reviews = sum(df.Negative_Review == "No Negative")
print("Number of No Negative reviews: " + str(no_negative_reviews))

no_positive_reviews = sum(df.Positive_Review == "No Positive")
print("Number of No Positive reviews: " + str(no_positive_reviews))

both_no_reviews = sum((df.Negative_Review == "No Negative") & (df.Positive_Review == "No Positive"))
print("Number of both No Negative and No Positive reviews: " + str(both_no_reviews))

Number of No Negative reviews: 127890
Number of No Positive reviews: 35946
Number of both No Negative and No Positive reviews: 127